
target :FoundationExtensionsApp do
  platform :osx, '10.7'
end

target :FoundationExtensionsIOSApp do
  platform :ios, '5.0'
end

target :FoundationExtensionsIOSAppTests do
  platform :ios, '5.0'
  pod 'Kiwi'
end
